### PR TITLE
Fix OOME on Node Rotation Keyframes

### PR DESCRIPTION
**Pull request by Danil0v3s**
This PR aims to fix an Out of Memory Exception resulting from an infinite loop on [ModelLoader.cs](https://github.com/daniloleemes/unityro/blob/0dcdd4c217762784cf8ac418c0df1338ae61832d/Assets/Scripts/Loaders/ModelLoader.cs#L253).

While using kRO grf and loading Prontera, at some point that `rkfCount` value is some random huge number. I couldn't find out why and what is wrong, except that changing the `rkfCount` to `short` will fix the problem as when casting to a lower number it downs to 0. My guess is that something is not right at `BinaryReader` but couldn't find anything super wrong there

After this fix every map should load normally. I still need to create some Unit Tests to make sure this kind of things always load as expected, other than that should we create a Discord so others could join and discuss easily?

Edit: Perhaps we should include the entire unity solution here as well?

### CODE REVIEW

**Comment by guilhermelhr** [comment]
That may be related to system configuration aswell since I can load Prontera just fine.
I've created a [Discord server](https://discord.gg/YZjGanTNb5). Good idea. Maybe you could share that GRF there so I can test it.

Publishing the entire solution would be nice too. We need to generate a new tag with your fixes.

**Comment by guilhermelhr** [comment]
https://github.com/Borf/browedit/blob/4b9444e54bcb17de8304d9d4ded0b560d43db4f5/brolib/BroLib/Rsm2.cpp#L148
https://github.com/greenboxal/FimbulwinterClient/blob/3cf059b53c579a41f0e8528feaf7a0e32058dfca/ROFormats/ROFormats/Model.cs#L245
https://github.com/open-ragnarok/roint/blob/2e98ec816e3a42864e2bf463f9cdf8869bfd5436/rsm.c#L183
https://github.com/vthibault/roBrowser/blob/e4b5b53aa1f8b7e429bfa987ab321c96502ba1da/src/Loaders/Model.js#L332

All these sources read `rkfCount` as a signed 32 bit integer aswell. That leads me to think that there is an anomaly on that GRF's Prontera.

I see the value that gets assigned to it is `1851878480`, and casting to `short` makes it [27728](https://dotnetfiddle.net/38Qah8), which gets the expected behavior. I'm not sure what to make of this since using `data.ReadShort()` breaks all maps.

Well, your solution works though, so I'll merge it.

**Comment by Danil0v3s** [comment]
Well, my first thought was to zero that variable if it's grater than short MAX or any other reasonable value.

I can see that even if it works the map loader is still iterating a bunch of times. What do you think?

**Comment by guilhermelhr** [comment]
I tested zeroing like you suggested, it broke model loading on all maps I've tested. Casting to short seems to be the only working solution.
I think maybe we could do:
```
int rkfCount = data.ReadLong();

// account for anomaly in kRO GRF's Prontera
if (rkfCount == 1851878480){
    rkfCount = (short) rkfCount;
}
```
That way we don't risk breaking any other situation where rkfCount is indeed a 32 bit integer.

**Comment by guilhermelhr** [comment]
Though I don't think it is likely that a model will have more than 32767 (signed short max) rotation keyframes.
The most I have seen is like a few hundred.

**Comment by sky-danilomenezes** [comment]
> Though I don't think it is likely that a model will have more than 32767 (signed short max) rotation keyframes.
> The most I have seen is like a few hundred.

I was going to say exactly that... We should have a function inside BinaryReader to cap that to avoid ifs and casts

**Comment by Danil0v3s** [comment]
> Though I don't think it is likely that a model will have more than 32767 (signed short max) rotation keyframes.
> The most I have seen is like a few hundred.

I was going to say exactly that... We should have a function inside BinaryReader to cap that to avoid ifs and casts

**Pull request merged**
